apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-ui-ingress
spec:
  rules:
  - host: {{.url}}
    http:
      paths:
      - path: /
        backend:
          serviceName: node-ui-service
          servicePort: 3000
