apiVersion: v1
kind: Service
metadata:
  name: node-ui-service
  labels:
    name: node-ui-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: node-ui
